name: Run security check with retire.js

on:
  push:
    branches:
      - f24
  pull_request:
    branches:
      - f24
  workflow_call:

jobs:
  retirejs-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install Retire.js
        run: npm install -g retire

      - name: Run Retire.js vulnerability scan
        run: retire
